openapi: 3.0.0
info:
  title: Ethereum RPC API
  description: Ethereum blockchain JSON-RPC API spec designed for the `eth_getStorageAt` method.
  version: 1.0.0
  externalDocs:
    url: "https://docs.grove.city"
  license:
    name: MIT License
    url: "https://github.com/pokt-foundation/grove-path/blob/main/LICENSE.md"
servers:
  - url: https://eth-mainnet.rpc.grove.city/v1/7ebb2846
    description: Ethereum Mainnet RPC Server
paths:
  /:
    post:
      operationId: eth_getStorageAt
      summary: Returns the value from a storage position at a given address.
      tags:
        - Ethereum RPC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  enum:
                    - "eth_getStorageAt"
                  example: "eth_getStorageAt"
                params:
                  type: array
                  items:
                    - type: string
                      pattern: "^0x[a-fA-F0-9]{40}$"
                      description: Account address in hexadecimal format.
                    - type: string
                      description: The storage position in the contract (as a hex).
                    - oneOf:
                        - type: string
                          description: HEX String - an integer block number
                        - type: string
                          enum:
                            - "latest"
                            - "earliest"
                            - "pending"
                            - "safe"
                            - "finalized"
                          description: Block parameter (e.g., 'latest', 'earliest', block number in hex).
                  minItems: 3
                  maxItems: 3
                  example:
                    [
                      "0x407d73d8a49eeb85d32cf465507dd71d507100c1",
                      "0x0",
                      "latest",
                    ]
                id:
                  $ref: "#/components/schemas/IdType"
              required:
                - jsonrpc
                - method
                - params
                - id
      responses:
        "200":
          description: The requested storage value.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    IdType:
      oneOf:
        - type: integer
          example: 1
        - type: string
          example: "myId"
    SuccessResponse:
      type: object
      description: The storage value at the specified location in hex.
      properties:
        jsonrpc:
          type: string
        id:
          $ref: "#/components/schemas/IdType"
        result:
          type: string
          example: "0x00000000000000000000000000000000000000000000000000000000000004d2"
      required:
        - jsonrpc
        - id
        - result
    ErrorResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/IdType"
        jsonrpc:
          type: string
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
              example: "Method not found"
            data:
              oneOf:
                - type: string
                - type: object
          required:
            - code
            - message
      required:
        - id
        - jsonrpc
        - error
