openapi: 3.0.0
info:
  title: Grove Ethereum Node API
  description: This is a hypothetical Grove Ethereum Node JSON-RPC API spec for retrieving hashrate.
  version: 1.0.0
servers:
  - url: https://eth-mainnet.rpc.grove.city/v1/7ebb2846 # Replace with actual URL if different
    description: Grove Ethereum Mainnet RPC Server
paths:
  /:
    post:
      operationId: eth_hashrate
      summary: Returns the hashrate of a given Ethereum node.
      tags:
        - Ethereum Node
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  enum:
                    - "eth_hashrate"
                  example: "eth_hashrate"
                params:
                  type: array
                  items:
                    type: string
                    description: Ethereum node address in hexadecimal format.
                  minItems: 1
                  example: ["0x<NODE_ADDRESS>"]
                id:
                  $ref: "#/components/schemas/IdType"
              required:
                - jsonrpc
                - method
                - params
                - id
      responses:
        "200":
          description: A JSON object containing the hashrate of the node
          content:
            application/json:
              schema:
                oneOf:
                  # Grove API does not currently support this method
                  # - $ref: '#/components/schemas/SuccessResponse'
                  - $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    IdType:
      oneOf:
        - type: integer
          example: 1
        - type: string
          example: "myId"
    SuccessResponse:
      type: object
      properties:
        jsonrpc:
          type: string
        id:
          $ref: "#/components/schemas/IdType"
        result:
          type: string
          description: Hashrate of the Ethereum node in HEX (e.g., 0x1234abcd)
      required:
        - jsonrpc
        - id
        - result
    ErrorResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/IdType"
        jsonrpc:
          type: string
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
              example: "Method not found"
            data:
              oneOf:
                - type: string
                - type: object
          required:
            - code
            - message
      required:
        - id
        - jsonrpc
        - error
