openapi: 3.0.0
info:
  title: Ethereum JSON-RPC API
  description: Ethereum blockchain JSON-RPC API spec designed for the `web3_sha3` method.
  version: 1.0.0
servers:
  - url: https://eth-mainnet.rpc.grove.city/v1/7ebb2846
    description: Ethereum Mainnet RPC Server
paths:
  /:
    post:
      operationId: web3_sha3
      summary: Calculates the Keccak-256 hash of the given data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jsonrpc:
                  type: string
                  example: "2.0"
                method:
                  type: string
                  enum:
                    - "web3_sha3"
                  example: "web3_sha3"
                params:
                  type: array
                  items:
                    type: string
                  example: ["0x68656c6c6f20776f726c64"]
                id:
                  oneOf:
                    - type: integer
                      example: 1
                    - type: string
                      example: "myId"
              required:
                - jsonrpc
                - method
                - id
      responses:
        "200":
          description: Response from the server.
          content:
            application/json:
              schema:
                oneOf:
                  # Grove API does not currently support this method
                  # - $ref: '#/components/schemas/SuccessResponse'
                  - $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    SuccessResponse:
      type: object
      properties:
        id:
          type: integer
        jsonrpc:
          type: string
        result:
          type: string
    ErrorResponse:
      type: object
      properties:
        id:
          type: integer
        jsonrpc:
          type: string
        error:
          type: object
          properties:
            code:
              type: integer
            message:
              type: string
              example: "Method not found"
            data:
              oneOf:
                - type: string
                - type: object
          required:
            - code
            - message
      required:
        - id
        - jsonrpc
        - error
